//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wallpapersetting.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wallpapersetting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 # Setting
        ///Setting=Wallpaper Setting
        ///settingOk=OK
        ///settingCancel=Cancel
        ///
        ///# Video
        ///videoLabel=Video
        ///videoBrowser=Browser
        ///
        ///# Wallpaper
        ///wallpaperLabel=General
        ///wallpaperAutorun=Run at startup
        ///wallpaperMenu=Desktop menu
        ///wallpaperExclude=Enable exclude
        ///
        ///# Stop
        ///exitClose=Exit
        ///exitClear=Cleanup
        ///
        ///# Exclude
        ///excludeLabel=Exclude
        ///excludeAdd=Add
        ///excludeDelete=Delete
        ///
        ///# Message
        ///information=Information
        ///warning=Warning
        ///closeMessage=Change not saved, are you sure to close?
        ///exitMessage=Are you sure t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # Setting
        ///Setting=Wallpaper设置
        ///settingOk=确定
        ///settingCancel=取消
        ///
        ///# Video
        ///videoLabel=视频
        ///videoBrowser=浏览
        ///
        ///# Wallpaper
        ///wallpaperLabel=通用
        ///wallpaperAutorun=开机启动
        ///wallpaperMenu=桌面右键菜单
        ///wallpaperExclude=启用排除项
        ///
        ///# Stop
        ///exitClose=退出
        ///exitClear=清理
        ///
        ///# Exclude
        ///excludeLabel=排除项
        ///excludeAdd=添加
        ///excludeDelete=删除
        ///
        ///# Message
        ///information=通知
        ///warning=警告
        ///closeMessage=修改还没有保存，确认要退出吗？
        ///exitMessage=确认要清理并退出“Wallpaper”吗？
        ///exitDone=清理完成。
        ///stopTipText=点击“帮助”以启用“清理”。
        /// 的本地化字符串。
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
